[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_user = odoo
db_password = odoo
db_name = univ_sms_db
admin_passwd = $pbkdf2-sha512$600000$G2PMGSMkpLT2HoMQ4vwfww$ZDrijQFgVFeGP5lzocXhABqH9qRjduGFMgLVLEi.Q299UD4Cj6GFj2xZDINwXUI4020.dT5E9xM0RA1CLzNa2A

